spring:
  application:
    name: digiotest

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

server:
  servlet:
    contextPath: "/digiotest"